FROM docker.io/library/rust:1.62

COPY hello-oci hello-oci

WORKDIR /hello-oci

RUN cargo build --release

FROM gcr.io/distroless/cc

COPY --from=0 /hello-oci/target/release/hello-oci /hello-oci

ENTRYPOINT ["/hello-oci"]
