FROM docker.io/library/rust:1.62

RUN rustup target add wasm32-wasi

COPY hello-wasm hello-wasm

WORKDIR /hello-wasm

RUN cargo build --release --target wasm32-wasi

FROM scratch

COPY --from=0 /hello-wasm/target/wasm32-wasi/release/hello-wasm.wasm /hello-wasm.wasm

CMD "/hello-wasm.wasm"
