#!/usr/bin/env bash

set -e

source "$(dirname "$0")/common"

check_auth

pushd "$REPO_ROOT/terraform"
HOSTNAME=$(terraform output -raw hostname)
PROJECT=$(terraform output -raw project)
ZONE=$(terraform output -raw zone)
popd

gcloud compute ssh --zone "$ZONE" --project "$PROJECT" "$HOSTNAME" --command "cd $REPO && scripts/run-benchmarks"
